# Generated by Django 4.2.11 on 2024-03-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='reviewer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
